# Generated by Django 5.2.3 on 2026-03-13 13:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has verified their email address.', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Phone number with country code (e.g., +213 123 456 789)', max_length=20, null=True, verbose_name='phone number')),
                ('address', models.TextField(blank=True, help_text='Complete address', null=True, verbose_name='address')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='gender')),
                ('bio', models.TextField(blank=True, help_text='Brief description about yourself', max_length=500, null=True, verbose_name='biography')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/%Y/%m/', verbose_name='avatar')),
                ('website', models.URLField(blank=True, help_text='Personal website or social media profile', null=True, verbose_name='website')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='occupation')),
                ('organization', models.CharField(blank=True, help_text='Company, school, or organization', max_length=100, null=True, verbose_name='organization')),
                ('student_id', models.CharField(blank=True, help_text='Student identification number', max_length=50, null=True, verbose_name='student ID')),
                ('employee_id', models.CharField(blank=True, help_text='Employee identification number', max_length=50, null=True, verbose_name='employee ID')),
                ('language_preference', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic'), ('en', 'English')], default='fr', max_length=10, verbose_name='language preference')),
                ('timezone', models.CharField(default='Africa/Algiers', max_length=50, verbose_name='timezone')),
                ('receive_notifications', models.BooleanField(default=True, help_text='Receive email notifications about library activities', verbose_name='receive notifications')),
                ('receive_newsletter', models.BooleanField(default=False, help_text='Receive newsletter and updates', verbose_name='receive newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
