# Generated by Django 5.2.3 on 2025-06-24 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (Français)')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Nom (Arabe)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (Français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabe)')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur')),
                ('icon', models.CharField(default='fas fa-calendar', max_length=50, verbose_name='Icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Catégorie d'événement",
                'verbose_name_plural': "Catégories d'événements",
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Titre (Arabe)')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description_fr', models.TextField(verbose_name='Description (Français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabe)')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name="Date limite d'inscription")),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('address', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Salle')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre maximum de participants')),
                ('registration_required', models.BooleanField(default=False, verbose_name='Inscription requise')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'inscription")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='draft', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorité')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name='Image')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='events/attachments/', verbose_name='Pièce jointe')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('notification', 'Notification')], max_length=20, verbose_name='Type de rappel')),
                ('send_before_hours', models.PositiveIntegerField(verbose_name='Envoyer X heures avant')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Rappel d'événement",
                'verbose_name_plural': "Rappels d'événements",
                'ordering': ['send_before_hours'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('attended', 'Présent'), ('absent', 'Absent')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Besoins spéciaux')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Événement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription à un événement',
                'verbose_name_plural': 'Inscriptions aux événements',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
