# Generated by Django 5.2.3 on 2026-02-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_fr', models.CharField(max_length=255, verbose_name='Texte (français)')),
                ('text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte (anglais)')),
                ('text_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte (arabe)')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Image gauche')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Image droite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Bandeau',
                'verbose_name_plural': 'Bandeaux',
            },
        ),
    ]
