# Generated by Django 5.2.3 on 2026-02-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='text_ar',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text_fr',
        ),
        migrations.AddField(
            model_name='banner',
            name='text1_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 1 (arabe)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text1_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 1 (anglais)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text1_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 1 (français)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text2_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 2 (arabe)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text2_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 2 (anglais)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text2_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 2 (français)'),
        ),
    ]
