# Generated by Django 5.2.3 on 2026-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_remove_banner_text_ar_remove_banner_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text3_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 3 (arabe)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text3_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 3 (anglais)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text3_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte 3 (français)'),
        ),
    ]
