# Generated by Django 5.2.3 on 2026-03-24 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle_fr', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('location_fr', models.CharField(blank=True, default='', max_length=255)),
                ('location_ar', models.CharField(blank=True, default='', max_length=255)),
                ('location_en', models.CharField(blank=True, default='', max_length=255)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_teams', models.IntegerField(default=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='hackathon/banners/')),
                ('is_active', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2024)),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hackathon/gallery/')),
                ('caption_fr', models.CharField(blank=True, default='', max_length=255)),
                ('caption_ar', models.CharField(blank=True, default='', max_length=255)),
                ('caption_en', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='hackathon.hackathonevent')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(default=1)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.CharField(blank=True, default='0', max_length=50)),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('is_special', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='hackathon.hackathonevent')),
            ],
            options={
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='hackathon.hackathonevent')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('time', models.CharField(help_text='Format HH:MM', max_length=5)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_fr', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('is_highlight', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='hackathon.hackathonevent')),
            ],
            options={
                'ordering': ['day', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('project_name_fr', models.CharField(max_length=255)),
                ('project_name_ar', models.CharField(blank=True, default='', max_length=255)),
                ('project_name_en', models.CharField(blank=True, default='', max_length=255)),
                ('project_description_fr', models.TextField(blank=True, default='')),
                ('project_description_ar', models.TextField(blank=True, default='')),
                ('project_description_en', models.TextField(blank=True, default='')),
                ('place', models.IntegerField(default=1)),
                ('members', models.TextField(blank=True, default='', help_text='Comma-separated member names')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hackathon/winners/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='hackathon.hackathonevent')),
            ],
            options={
                'ordering': ['place'],
            },
        ),
    ]
