# Generated by Django 5.2.3 on 2026-02-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (Français)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Nom (Arabe)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (Français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabe)')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: network, cpu, radio)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de formation',
                'verbose_name_plural': 'Catégories de formations',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Titre (Arabe)')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Label (ex: Bootcamp, Introduction)')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description_fr', models.TextField(verbose_name='Description courte (Français)')),
                ('description_ar', models.TextField(verbose_name='Description courte (Arabe)')),
                ('content_fr', models.TextField(blank=True, verbose_name='Contenu complet (Français)')),
                ('content_ar', models.TextField(blank=True, verbose_name='Contenu complet (Arabe)')),
                ('objectives_fr', models.TextField(blank=True, verbose_name='Objectifs (Français)')),
                ('objectives_ar', models.TextField(blank=True, verbose_name='Objectifs (Arabe)')),
                ('prerequisites_fr', models.TextField(blank=True, verbose_name='Prérequis (Français)')),
                ('prerequisites_ar', models.TextField(blank=True, verbose_name='Prérequis (Arabe)')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='Niveau')),
                ('duration_weeks', models.PositiveIntegerField(default=1, verbose_name='Durée (semaines)')),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (heures)')),
                ('max_students', models.PositiveIntegerField(default=20, verbose_name="Nombre maximum d'étudiants")),
                ('image', models.ImageField(blank=True, null=True, upload_to='ohb_formations/images/', verbose_name='Image')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ohb_formations/pdfs/', verbose_name='PDF du cours')),
                ('brochure_pdf', models.FileField(blank=True, null=True, upload_to='ohb_formations/brochures/', verbose_name='Brochure PDF')),
                ('price', models.CharField(default='0', max_length=20, verbose_name='Prix (TND)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuit')),
                ('registration_open', models.BooleanField(default=True, verbose_name='Inscription ouverte')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='ohb_formation.formationcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Formation OHB',
                'verbose_name_plural': 'Formations OHB',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormationEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name="Nom de l'étudiant")),
                ('student_email', models.EmailField(max_length=254, verbose_name="Email de l'étudiant")),
                ('student_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='ohb_formation.formation')),
            ],
            options={
                'verbose_name': 'Inscription formation',
                'verbose_name_plural': 'Inscriptions formations',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
