# Generated by Django 5.2.3 on 2026-02-14 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohb_formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ohb_formations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='formation',
            name='daily_organization_ar',
            field=models.TextField(blank=True, verbose_name='Organisation journalière (Arabe)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='daily_organization_fr',
            field=models.TextField(blank=True, verbose_name='Organisation journalière (Français)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='daily_program_ar',
            field=models.TextField(blank=True, verbose_name='Programme par jour (Arabe)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='daily_program_fr',
            field=models.TextField(blank=True, verbose_name='Programme par jour (Français)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='location_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu (Arabe)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='location_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu (Français)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='target_audience_ar',
            field=models.TextField(blank=True, verbose_name='Public cible (Arabe)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='target_audience_fr',
            field=models.TextField(blank=True, verbose_name='Public cible (Français)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='teaching_methods_ar',
            field=models.TextField(blank=True, verbose_name='Méthodes pédagogiques (Arabe)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='teaching_methods_fr',
            field=models.TextField(blank=True, verbose_name='Méthodes pédagogiques (Français)'),
        ),
    ]
