# Generated by Django 5.2.3 on 2026-02-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohb_formation', '0002_formation_created_by_formation_daily_organization_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='price',
        ),
    ]
