# Generated by Django 5.2.3 on 2026-03-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumEquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (Français)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Nom (Arabe)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (Français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabe)')),
                ('color', models.CharField(default='#3B82F6', help_text='Couleur hexadécimale', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Catégorie d'équipement",
                'verbose_name_plural': "Catégories d'équipements",
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='MuseumEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=200, verbose_name='Nom (Français)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Nom (Arabe)')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description_fr', models.TextField(verbose_name='Description (Français)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabe)')),
                ('historical_context_fr', models.TextField(blank=True, verbose_name='Contexte historique (Français)')),
                ('historical_context_ar', models.TextField(blank=True, verbose_name='Contexte historique (Arabe)')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Bon état'), ('fair', 'État moyen'), ('poor', 'Mauvais état'), ('restoring', 'En restauration')], default='good', max_length=20, verbose_name='État de conservation')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('on_display', 'En exposition'), ('on_loan', 'En prêt'), ('stored', 'En stockage')], default='available', max_length=20, verbose_name='Statut')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'inventaire")),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('acquisition_method', models.CharField(blank=True, max_length=100, verbose_name="Mode d'acquisition")),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name="Origine/Pays d'origine")),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Dimensions')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Poids')),
                ('image', models.ImageField(blank=True, null=True, upload_to='museum/equipment/', verbose_name='Image')),
                ('image_alt_fr', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif image (Français)')),
                ('image_alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif image (Arabe)')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('featured_image', models.BooleanField(default=False, verbose_name='Image en héros')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='Période')),
                ('production_date', models.CharField(blank=True, max_length=100, verbose_name='Date de production')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museum_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.museumequipmentcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuseumPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Nom complet')),
                ('role', models.CharField(choices=[('scientist', 'Scientifique'), ('engineer', 'Ingénieur'), ('inventor', 'Inventeur'), ('researcher', 'Chercheur'), ('teacher', 'Enseignant'), ('director', 'Directeur'), ('military', 'Militaire'), ('politician', 'Homme politique'), ('artist', 'Artiste'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Rôle')),
                ('role_custom_fr', models.CharField(blank=True, max_length=100, verbose_name='Rôle personnalisé (Français)')),
                ('role_custom_ar', models.CharField(blank=True, max_length=100, verbose_name='Rôle personnalisé (Arabe)')),
                ('biography_fr', models.TextField(verbose_name='Biographie (Français)')),
                ('biography_ar', models.TextField(verbose_name='Biographie (Arabe)')),
                ('achievements_fr', models.TextField(blank=True, verbose_name='Réalisations (Français)')),
                ('achievements_ar', models.TextField(blank=True, verbose_name='Réalisations (Arabe)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('death_place', models.CharField(blank=True, max_length=200, verbose_name='Lieu de décès')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='museum/personality/', verbose_name='Photo')),
                ('photo_alt_fr', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif photo (Français)')),
                ('photo_alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif photo (Arabe)')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='museum_personalities', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('equipment', models.ManyToManyField(blank=True, related_name='personalities', to='museum.museumequipment', verbose_name='Équipements associés')),
            ],
            options={
                'verbose_name': 'Personnalité',
                'verbose_name_plural': 'Personnalités',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
