# Generated by Django 5.2.3 on 2026-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du rédacteur (FR)')),
                ('reviewer_name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المراجع (AR)')),
                ('reviewer_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reviewer Name (EN)')),
                ('content_fr', models.TextField(blank=True, null=True, verbose_name='Contenu (FR)')),
                ('content_ar', models.TextField(blank=True, null=True, verbose_name='المحتوى (AR)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Content (EN)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Note / تقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le / أنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le / تم التحديث في')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/photos/', verbose_name='Photo')),
                ('reviewer_type', models.CharField(choices=[('visitor', 'Visiteur / زائر'), ('student', 'Étudiant / طالب'), ('sponsor', 'Sponsor / راعي')], max_length=20, verbose_name='Type de rédacteur / نوع المراجع')),
            ],
        ),
    ]
