# Generated by Django 5.2.1 on 2025-05-25 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (Français)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Nom (Arabe)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (Français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabe)')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: network, cpu, radio)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de cours',
                'verbose_name_plural': 'Catégories de cours',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Titre (Arabe)')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description_fr', models.TextField(verbose_name='Description courte (Français)')),
                ('description_ar', models.TextField(verbose_name='Description courte (Arabe)')),
                ('content_fr', models.TextField(verbose_name='Contenu détaillé (Français)')),
                ('content_ar', models.TextField(verbose_name='Contenu détaillé (Arabe)')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], max_length=20, verbose_name='Niveau')),
                ('duration_weeks', models.PositiveIntegerField(verbose_name='Durée (semaines)')),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (heures)')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name="Nombre max d'étudiants")),
                ('image', models.ImageField(upload_to='courses/images/', verbose_name='Image du cours')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de la vidéo de présentation')),
                ('prerequisites_fr', models.TextField(blank=True, verbose_name='Prérequis (Français)')),
                ('prerequisites_ar', models.TextField(blank=True, verbose_name='Prérequis (Arabe)')),
                ('objectives_fr', models.TextField(blank=True, verbose_name='Objectifs (Français)')),
                ('objectives_ar', models.TextField(blank=True, verbose_name='Objectifs (Arabe)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('registration_open', models.BooleanField(default=True, verbose_name='Inscription ouverte')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name="Date limite d'inscription")),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name='Cours mis en avant')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Cours OHB',
                'verbose_name_plural': 'Cours OHB',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('title_fr', models.CharField(max_length=100, verbose_name='Titre/Poste (Français)')),
                ('title_ar', models.CharField(max_length=100, verbose_name='Titre/Poste (Arabe)')),
                ('bio_fr', models.TextField(blank=True, verbose_name='Biographie (Français)')),
                ('bio_ar', models.TextField(blank=True, verbose_name='Biographie (Arabe)')),
                ('photo', models.ImageField(blank=True, upload_to='instructors/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='courses.course')),
            ],
            options={
                'verbose_name': 'Instructeur',
                'verbose_name_plural': 'Instructeurs',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Titre (Arabe)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (Français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabe)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='Durée (heures)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Module de cours',
                'verbose_name_plural': 'Modules de cours',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name="Nom de l'étudiant")),
                ('student_email', models.EmailField(max_length=254, verbose_name="Email de l'étudiant")),
                ('student_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('motivation', models.TextField(blank=True, verbose_name='Lettre de motivation')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-enrolled_at'],
                'unique_together': {('course', 'student_email')},
            },
        ),
    ]
