# Generated by Django 5.2.1 on 2025-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='courses/pdfs/', verbose_name='Fichier PDF du cours'),
        ),
    ]
