# Generated by Django 5.2.1 on 2025-05-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='brochure_pdf',
            field=models.FileField(blank=True, upload_to='courses/brochures/', verbose_name='Brochure PDF du cours'),
        ),
    ]
