# Generated by Django 5.2.3 on 2025-12-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_brochure_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Label (ex: Bootcamp, Introduction)'),
        ),
    ]
