# Generated by Django 5.2.3 on 2025-12-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('ohb', 'OHB'), ('school', 'École')], default='ohb', max_length=10, verbose_name='Type de cours'),
        ),
    ]
