# Generated by Django 5.2.3 on 2025-12-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(blank=True, choices=[('inspecteur_technique_specialise', 'Inspecteur technique spécialisé'), ('assistant_technique_specialise', 'Assistant technique spécialisé'), ('agent_exploitation', "Agent d'exploitation")], max_length=50, null=True, verbose_name='Grade cible'),
        ),
    ]
