# Generated by Django 5.2.3 on 2026-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('ohb', 'OHB'), ('school', 'École')], default='school', max_length=10, verbose_name='Type de cours'),
        ),
    ]
