# Generated by Django 5.2.3 on 2026-03-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description (English)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (English)'),
        ),
    ]
