# Generated by Django 4.2.17 on 2026-04-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_description_en_course_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Detailed Content (English)'),
        ),
    ]
