# Generated by Django 5.2.3 on 2026-02-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (FR)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (AR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (FR)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='اللقب (AR)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('story_fr', models.TextField(verbose_name='Parcours / Succès (FR)')),
                ('story_ar', models.TextField(verbose_name='قصة النجاح (AR)')),
                ('story_en', models.TextField(verbose_name='Success Story (EN)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni/photos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
