# Generated by Django 5.2.3 on 2026-02-09 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_success', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alumni/gallery/')),
                ('legend_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('legend_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('legend_en', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='alumni_success.alumnisuccess')),
            ],
        ),
    ]
