# Generated by Django 5.2.3 on 2026-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (fr)')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (ar)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (en)')),
                ('message_fr', models.TextField(blank=True, verbose_name='Message (fr)')),
                ('message_ar', models.TextField(blank=True, null=True, verbose_name='Message (ar)')),
                ('message_en', models.TextField(blank=True, null=True, verbose_name='Message (en)')),
                ('start_year', models.PositiveIntegerField(verbose_name='Année de début')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de fin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='directors/')),
                ('is_current', models.BooleanField(default=False, verbose_name='Directeur actuel')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Directeur',
                'verbose_name_plural': 'Directeurs',
                'ordering': ['-is_current', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (fr)')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (ar)')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (en)')),
                ('role_fr', models.CharField(max_length=100, verbose_name='Rôle (fr)')),
                ('role_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rôle (ar)')),
                ('role_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rôle (en)')),
                ('bio_fr', models.TextField(blank=True, verbose_name='Bio (fr)')),
                ('bio_ar', models.TextField(blank=True, null=True, verbose_name='Bio (ar)')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Bio (en)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
