# Generated by Django 5.2.1 on 2025-05-25 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (Français)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Nom (Arabe)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (Français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabe)')),
                ('color', models.CharField(default='#3B82F6', help_text='Couleur hexadécimale', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Catégorie d'actualité",
                'verbose_name_plural': "Catégories d'actualités",
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'abonnement")),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de désabonnement')),
            ],
            options={
                'verbose_name': 'Abonnement newsletter',
                'verbose_name_plural': 'Abonnements newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=50, unique=True, verbose_name='Nom (Français)')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Nom (Arabe)')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Titre (Arabe)')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('summary_fr', models.TextField(max_length=500, verbose_name='Résumé (Français)')),
                ('summary_ar', models.TextField(max_length=500, verbose_name='Résumé (Arabe)')),
                ('content_fr', models.TextField(verbose_name='Contenu (Français)')),
                ('content_ar', models.TextField(verbose_name='Contenu (Arabe)')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('featured_image', models.ImageField(upload_to='news/images/', verbose_name='Image à la une')),
                ('image_alt_fr', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif image (Français)')),
                ('image_alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif image (Arabe)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('featured', models.BooleanField(default=False, verbose_name='Article mis en avant')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Autoriser les commentaires')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('meta_description_fr', models.CharField(blank=True, max_length=160, verbose_name='Meta description (Français)')),
                ('meta_description_ar', models.CharField(blank=True, max_length=160, verbose_name='Meta description (Arabe)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Nom de l'auteur")),
                ('author_email', models.EmailField(max_length=254, verbose_name="Email de l'auteur")),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_tags', to='news.news')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_news', to='news.newstag')),
            ],
            options={
                'verbose_name': "Tag d'actualité",
                'verbose_name_plural': "Tags d'actualités",
                'unique_together': {('news', 'tag')},
            },
        ),
    ]
