# Generated by Django 5.2.3 on 2025-12-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Titre (Arabe)')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('year', models.PositiveIntegerField(help_text='Année du succès', verbose_name='Année')),
                ('summary_fr', models.TextField(max_length=500, verbose_name='Résumé (Français)')),
                ('summary_ar', models.TextField(max_length=500, verbose_name='Résumé (Arabe)')),
                ('content_fr', models.TextField(verbose_name='Contenu (Français)')),
                ('content_ar', models.TextField(verbose_name='Contenu (Arabe)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='alumni/images/', verbose_name='Image')),
                ('image_alt_fr', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif image (Français)')),
                ('image_alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif image (Arabe)')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_successes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': "Succès d'ancien",
                'verbose_name_plural': 'Succès des anciens',
                'ordering': ['-year', '-published_at'],
            },
        ),
    ]
