# Generated by Django 5.2.3 on 2025-12-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alumnisuccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alumni/photos/', verbose_name='Photo')),
                ('caption_fr', models.CharField(blank=True, max_length=200, verbose_name='Légende (Français)')),
                ('caption_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (العربية)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='news.alumnisuccess')),
            ],
            options={
                'verbose_name': "Photo d'ancien",
                'verbose_name_plural': 'Photos des anciens',
                'ordering': ['-created_at'],
            },
        ),
    ]
