# Generated by Django 5.2.1 on 2025-05-25 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('view_course', 'Consultation cours'), ('enroll_course', 'Inscription cours'), ('view_news', 'Consultation actualité'), ('borrow_book', 'Emprunt livre'), ('download_book', 'Téléchargement livre'), ('add_review', 'Ajout avis'), ('profile_update', 'Mise à jour profil')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('content_type', models.CharField(blank=True, max_length=50, verbose_name='Type de contenu')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('course', 'Cours'), ('news', 'Actualité'), ('library', 'Bibliothèque'), ('system', 'Système')], default='info', max_length=20, verbose_name='Type')),
                ('link_url', models.URLField(blank=True, verbose_name='Lien')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Texte du lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('staff', 'Personnel'), ('admin', 'Administrateur'), ('visitor', 'Visiteur')], default='visitor', max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro étudiant')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro employé')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('country', models.CharField(default='Algérie', max_length=100, verbose_name='Pays')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Spécialisation')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='Année académique')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name="Date d'inscription")),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('en', 'Anglais')], default='fr', max_length=10, verbose_name='Langue préférée')),
                ('receive_notifications', models.BooleanField(default=True, verbose_name='Recevoir les notifications')),
                ('receive_newsletter', models.BooleanField(default=False, verbose_name='Recevoir la newsletter')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('is_active_student', models.BooleanField(default=True, verbose_name='Étudiant actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Informations appareil')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'ordering': ['-last_activity'],
            },
        ),
    ]
