# Generated by Django 5.2.3 on 2025-06-24 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('login_notification', 'Notification de connexion'), ('admin_response', 'Réponse administrateur'), ('user_message', 'Message utilisateur'), ('system_alert', 'Alerte système')], default='user_message', max_length=30)),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('admin_response', models.TextField(blank=True, verbose_name='Réponse administrateur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('responded', 'Répondu'), ('closed', 'Fermé')], default='pending', max_length=20)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de connexion')),
                ('login_device', models.CharField(blank=True, max_length=200, verbose_name='Appareil de connexion')),
                ('login_location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Administrateur-Utilisateur',
                'verbose_name_plural': 'Messages Administrateur-Utilisateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
