# Generated by Django 5.2.3 on 2025-06-24 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminusermessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('welcome', 'Email de bienvenue'), ('course_enrollment', 'Inscription à un cours'), ('book_reservation', 'Réservation de livre'), ('event_registration', 'Inscription à un événement'), ('event_reminder', "Rappel d'événement"), ('password_reset', 'Réinitialisation de mot de passe'), ('admin_notification', 'Notification admin'), ('custom', 'Personnalisé')], max_length=50, unique=True, verbose_name='Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('html_content', models.TextField(verbose_name='Contenu HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('available_variables', models.TextField(blank=True, help_text='Variables disponibles: {{user_name}}, {{user_email}}, {{site_name}}, etc.', verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Template d'email",
                'verbose_name_plural': "Templates d'emails",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email destinataire')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('html_content', models.TextField(blank=True, verbose_name='Contenu HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('bounced', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Ouvert le')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Cliqué le')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur destinataire')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': "Log d'email",
                'verbose_name_plural': "Logs d'emails",
                'ordering': ['-created_at'],
            },
        ),
    ]
