# Generated by Django 5.2.3 on 2025-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailtemplate_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('role_fr', models.CharField(max_length=100, verbose_name='Rôle (Français)')),
                ('role_ar', models.CharField(max_length=100, verbose_name='Rôle (Arabe)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (Français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabe)')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('is_director', models.BooleanField(default=False, verbose_name='Est le directeur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'verbose_name_plural': "Membres d'équipe",
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
