# Generated by Django 5.2.3 on 2025-12-13 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'created_at'], 'verbose_name': "Membre de l'équipe", 'verbose_name_plural': "Membres de l'équipe"},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='teammember',
            name='courses_taught',
            field=models.TextField(blank=True, help_text='Liste des cours (ex: Math, Physique)', verbose_name='Cours enseignés'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optionnel: lier à un utilisateur existant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='Est le Directeur'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo'),
        ),
    ]
